name = "workersql-gateway"
main = "src/gateway.ts"
compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "src/app/dist"
binding = "ASSETS"

[triggers]
crons = ["0 3 * * *"]

[env.development]
name = "workersql-gateway-dev"
vars = { ENVIRONMENT = "development", LOG_LEVEL = "info", MAX_SHARD_SIZE_GB = "10", CACHE_TTL_MS = "30000", CACHE_SWR_MS = "120000", BATCH_MAX_OPS = "2", BATCH_MAX_BYTES = "5120", ENFORCE_HTTPS = "true", ALLOW_COUNTRIES = "", BLOCK_COUNTRIES = "", ALLOW_IPS = "", BLOCK_IPS = "", AUDIT_RETENTION_DAYS = "90" }
compatibility_flags = ["nodejs_compat"]

[[env.development.kv_namespaces]]
binding = "APP_CACHE"
id = "cache_namespace_id"
preview_id = "cache_namespace_preview_id"

[[env.development.kv_namespaces]]
binding = "SESSION"
id = "session_namespace_id"
preview_id = "session_namespace_preview_id"

[[env.development.queues.producers]]
binding = "DB_EVENTS"
queue = "db-events"

[[env.development.queues.consumers]]
queue = "db-events"
max_batch_size = 50
max_batch_timeout = 2
max_retries = 3
dead_letter_queue = "db-events-dlq"

[[env.development.durable_objects.bindings]]
name = "SHARD"
class_name = "TableShard"

[[env.development.d1_databases]]
binding = "PORTABLE_DB"
database_name = "portable-mirror"
database_id = "d1_database_id"

[[env.development.analytics_engine_datasets]]
binding = "AUDIT_LOGS"
dataset = "audit_logs"

[[env.development.r2_buckets]]
binding = "AUDIT_LOGS_BUCKET"
bucket_name = "workersql-audit-dev"

[[env.development.r2_buckets]]
binding = "BACKUPS_BUCKET"
bucket_name = "workersql-backups-dev"

[env.staging]
name = "workersql-gateway-staging"

[[env.staging.analytics_engine_datasets]]
binding = "AUDIT_LOGS"
dataset = "audit_logs"

[[env.staging.r2_buckets]]
binding = "AUDIT_LOGS_BUCKET"
bucket_name = "workersql-audit-staging"

[[env.staging.r2_buckets]]
binding = "BACKUPS_BUCKET"
bucket_name = "workersql-backups-staging"

[env.production]
name = "workersql-gateway-prod"

[[env.production.analytics_engine_datasets]]
binding = "AUDIT_LOGS"
dataset = "audit_logs"

[[env.production.r2_buckets]]
binding = "AUDIT_LOGS_BUCKET"
bucket_name = "workersql-audit-prod"

[[env.production.r2_buckets]]
binding = "BACKUPS_BUCKET"
bucket_name = "workersql-backups-prod"

[[kv_namespaces]]
binding = "APP_CACHE"
id = "cache_namespace_id"
preview_id = "cache_namespace_preview_id"

# KV namespace for session storage (used by @astrojs/cloudflare sessions)
[[kv_namespaces]]
binding = "SESSION"
# TODO: Replace the placeholder IDs below with real values from `wrangler kv namespace create SESSION`
id = "session_namespace_id"
preview_id = "session_namespace_preview_id"

[[queues.producers]]
binding = "DB_EVENTS"
queue = "db-events"

[[queues.consumers]]
queue = "db-events"
max_batch_size = 50
max_batch_timeout = 2
max_retries = 3
dead_letter_queue = "db-events-dlq"

[[durable_objects.bindings]]
name = "SHARD"
class_name = "TableShard"

[[migrations]]
tag = "v1"
new_classes = ["TableShard"]

[[d1_databases]]
binding = "PORTABLE_DB"
database_name = "portable-mirror"
database_id = "d1_database_id"

[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "info"
MAX_SHARD_SIZE_GB = "10"
CACHE_TTL_MS = "30000"
CACHE_SWR_MS = "120000"
ENFORCE_HTTPS = "true"
ALLOW_COUNTRIES = ""
BLOCK_COUNTRIES = ""
ALLOW_IPS = ""
BLOCK_IPS = ""
AUDIT_RETENTION_DAYS = "90"
JWT_SECRET = "local-dev-secret"

[build]
command = "npm run build"
cwd = "."
watch_dir = ["src/gateway.ts", "src/services", "src/types", "src/app/src"]
