name = "workersql-gateway"
main = "src/gateway.ts"
compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]

[env.development]
name = "workersql-gateway-dev"
vars = { ENVIRONMENT = "development", LOG_LEVEL = "info", MAX_SHARD_SIZE_GB = "10", CACHE_TTL_MS = "30000", CACHE_SWR_MS = "120000", BATCH_MAX_OPS = "2", BATCH_MAX_BYTES = "5120" }
compatibility_flags = ["nodejs_compat"]

[[env.development.kv_namespaces]]
binding = "APP_CACHE"
id = "cache_namespace_id"
preview_id = "cache_namespace_preview_id"

[[env.development.kv_namespaces]]
binding = "SESSION"
id = "session_namespace_id"
preview_id = "session_namespace_preview_id"

[[env.development.queues.producers]]
binding = "DB_EVENTS"
queue = "db-events"

[[env.development.queues.consumers]]
queue = "db-events"
max_batch_size = 50
max_batch_timeout = 2
max_retries = 3
dead_letter_queue = "db-events-dlq"

[[env.development.durable_objects.bindings]]
name = "SHARD"
class_name = "TableShard"

[[env.development.d1_databases]]
binding = "PORTABLE_DB"
database_name = "portable-mirror"
database_id = "d1_database_id"

[env.staging]
name = "workersql-gateway-staging"

[env.production]
name = "workersql-gateway-prod"

[[kv_namespaces]]
binding = "APP_CACHE"
id = "cache_namespace_id"
preview_id = "cache_namespace_preview_id"

# KV namespace for session storage (used by @astrojs/cloudflare sessions)
[[kv_namespaces]]
binding = "SESSION"
# TODO: Replace the placeholder IDs below with real values from `wrangler kv namespace create SESSION`
id = "session_namespace_id"
preview_id = "session_namespace_preview_id"

[[queues.producers]]
binding = "DB_EVENTS"
queue = "db-events"

[[queues.consumers]]
queue = "db-events"
max_batch_size = 50
max_batch_timeout = 2
max_retries = 3
dead_letter_queue = "db-events-dlq"

[[durable_objects.bindings]]
name = "SHARD"
class_name = "TableShard"

[[migrations]]
tag = "v1"
new_classes = ["TableShard"]

[[d1_databases]]
binding = "PORTABLE_DB"
database_name = "portable-mirror"
database_id = "d1_database_id"

[vars]
ENVIRONMENT = "development"
LOG_LEVEL = "info"
MAX_SHARD_SIZE_GB = "10"
CACHE_TTL_MS = "30000"
CACHE_SWR_MS = "120000"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"
