# n8n webhook entity table policy
primary_key: id
shard_by: webhook_id # Hash-based for load distribution

cache:
  mode: bounded
  ttl_ms: 300000 # 5 minutes
  swr_ms: 1800000 # 30 minutes
  always_strong_columns:
    - webhook_path

routing:
  strategy: table_hash
