# Example table policy configuration for orders table
primary_key: order_id
shard_by: user_id

cache:
  mode: strong
  ttl_ms: 60000 # 1 minute
  swr_ms: 300000 # 5 minutes

routing:
  strategy: table_hash
