# Example table policy configuration for users table
primary_key: id
shard_by: tenant_id

cache:
  mode: bounded
  ttl_ms: 300000 # 5 minutes
  swr_ms: 1800000 # 30 minutes
  always_strong_columns:
    - email
    - user_id

routing:
  strategy: tenant_hash
